=== rrazvanrraducanu/XML11/data.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="date" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Nume"/>
              <xs:element type="xs:string" name="Prenume"/>
              <xs:element type="xs:string" name="Username"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rrazvanrraducanu/XML11/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='data.xsd'>
<date>
        <Nume>Popescu</Nume>
        <Prenume>Ion</Prenume>
        <Username>pion</Username>
    </date>
    <date>
        <Nume>Georgescu</Nume>
        <Prenume>Mihai</Prenume>
        <Username>gmihai</Username>
    </date>
    <date>
        <Nume>Ionescu</Nume>
        <Prenume>Bogdan</Prenume>
        <Username>ibogdan</Username>
    </date>


</root>
